### ISSUE TITLE
[APL] StitchIfwi.py results in error

### ISSUE THREAD

**Issue by Sean-StarLabs** [slimbootloader/slimbootloader#1229]
Running StitchIfwi.py results in error:
```
Patching IBBL Flash map ...
Patching Slim Bootloader Flash Map table ...
Traceback (most recent call last):
  File "/home/sean/Documents/slimbootloader/Platform/ApollolakeBoardPkg/Script/StitchIfwi.py", line 651, in <module>
    sys.exit(main())
  File "/home/sean/Documents/slimbootloader/Platform/ApollolakeBoardPkg/Script/StitchIfwi.py", line 635, in main
    if stitch (stitch_dir, args.stitch_zip, args.btg_profile, args.quad_mode, args.plat_data):
  File "/home/sean/Documents/slimbootloader/Platform/ApollolakeBoardPkg/Script/StitchIfwi.py", line 549, in stitch
    ret = patch_ibb_flash_map (cfg_var['fitinput'] + '/Stitch_IBBL.bin', ifwi_file_name, platform_data)
  File "/home/sean/Documents/slimbootloader/Platform/ApollolakeBoardPkg/Script/StitchIfwi.py", line 147, in patch_ibb_flash_map
    ifwi = patch_flash_map (ifwi_img_data, platform_data)
  File "/home/sean/Documents/slimbootloader/Platform/ApollolakeBoardPkg/Script/StitchLoader.py", line 409, in patch_flash_map
    fla_map_str = FLASH_MAP.from_buffer (output_image_data, stage1AOffset + fla_map_off)
ValueError: Buffer size too small (8388608 instead of at least 2425951456 bytes)
```

2.25Gi doesn't sound right for an 8MB flash! Could this be a bug or is it down to config?

Built using Python 3.9.5 and GCC 10.3.0.

**Comment by Sean-StarLabs** [comment]
Issue was IPAD alignment
